# Generated by Django 3.2 on 2021-07-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='国',
        ),
    ]
