# Generated by Django 3.2 on 2021-07-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_rename_location_userprofile_国'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='写真',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='名前',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_date',
            new_name='誕生日',
        ),
    ]
