# Generated by Django 3.2 on 2021-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_userprofile_国'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='サイト',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
