# Generated by Django 3.2 on 2021-07-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userprofile_サイト'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='自己紹介',
        ),
    ]
