# Generated by Django 3.2 on 2021-07-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_rename_bio_userprofile_自己紹介'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='言語',
            field=models.CharField(choices=[('English', 'English'), ('日本語', '日本語'), ('ਪੰਜਾਬੀ', 'ਪੰਜਾਬੀ')], default=('日本語', '日本語'), max_length=900),
        ),
    ]
