# Generated by Django 3.2 on 2021-07-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20210719_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='国',
            field=models.CharField(blank=True, choices=[('アメリカ', 'アメリカ'), ('インド', 'インド'), ('メキシコ', 'メキシコ'), ('ドイツ', 'ドイツ'), ('韓国', '韓国'), ('北朝鮮', '北朝鮮'), ('台湾', '台湾'), ('日本', '日本')], max_length=6, null=True),
        ),
    ]
