# Generated by Django 3.2 on 2021-08-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_notification_from_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='名前',
            new_name='name',
        ),
    ]
